language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kiransai5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kiransai5/react-test npm test

after_success:
  - docker build -t kiransai5/multi-client ./client
  - docker build -t kiransai5/multi-nginx ./nginx
  - docker build -t kiransai5/multi-server ./server
  - docker build -t kiransai5/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kiransai5/multi-client
  - docker push kiransai5/multi-nginx
  - docker push kiransai5/multi-server
  - docker push kiransai5/multi-worker

deploy:
  provider:  elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-301869998560
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
